### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by Para-b0la** [alcatraz-rm/Text_tone_analyzer#11]
Добрый день!

По шагам пробовал запустить проект. Точно установлены все библиотеки, которые тут используются. Когда запускаю Demo.py появляется ошибка, которая ниже. В чем может быть проблема?
Спасибо.

Traceback (most recent call last):
  File "Demo.py", line 24, in <module>
    from Python.Services.FileReader import FileReader
ModuleNotFoundError: No module named 'Python'

**Comment by altblog** [comment]
Такая же проблема :(

**Comment by potassium-chloride** [comment]
Проблема в том, что автор объелся Явы. Скопируйте исполняемый файлы на уровень выше и попробуйте ещё раз (впрочем, у меня и после этого оно не заработало)
